# Generated by Django 6.0.1 on 2026-01-28 03:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_task_options_supervisorintern_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='supervisorintern',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='supervisorintern',
            name='progress_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supervisorintern',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_intern_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('intern', 'date'), name='uniq_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('intern', 'month'), name='uniq_report_per_month'),
        ),
    ]
