# Generated by Django 5.2.8 on 2026-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed_at_user_token_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
