// frontend/js/config.js
const API_BASE = "http://127.0.0.1:8000/api";
const ACCOUNTS_API = `${API_BASE}/accounts`;   // /api/accounts/...
const INTERNSHIPS_API = `${API_BASE}`;         // internships live directly under /api/...
const Attendance_API = `${API_BASE}/attendance`; // /api/attendance/...