// frontend/js/config.js

const API_BASE = "https://codavatarinterntracking-api.onrender.com/api";

const ACCOUNTS_API = `${API_BASE}/accounts`;      // /api/accounts/...
const INTERNSHIPS_API = `${API_BASE}`;            // /api/...
const ATTENDANCE_API = `${API_BASE}/attendance`;  // /api/attendance/...
